#include "TFile.h"
#include "TH1D.h"
#include "TCanvas.h"
#include "TPaveStats.h"
#include "THStack.h"
#include "TLegend.h"

void Plotmacro(){
  //gROOT->LoadMacro("tdrstyle.C");
  //setTDRStyle();
  
  TFile *f = new TFile("controlplots.root","READ");
  TH1D *EtaISR = (TH1D*) f->Get("h_EtaISR");
  EtaISR->GetYaxis()->SetTitle("Counts/0.12");
  EtaISR->GetYaxis()->SetTitleOffset(1.7);
  EtaISR->GetXaxis()->SetTitle("#eta");
  TH1D *CthISR = (TH1D*) f->Get("h_CthISR");
  CthISR->GetYaxis()->SetTitle("Counts/0.02");
  CthISR->GetYaxis()->SetTitleOffset(1.7);
  CthISR->GetYaxis()->SetRangeUser(0,70000);
  CthISR->GetXaxis()->SetTitle("Cos(#theta)");
  TH1D *PhiISR = (TH1D*) f->Get("h_PhiISR");
  PhiISR->GetYaxis()->SetTitle("Counts/0.064 rad");
  PhiISR->GetYaxis()->SetTitleOffset(1.7);
  PhiISR->GetXaxis()->SetTitle("#phi[rad]");
  PhiISR->GetYaxis()->SetRangeUser(0,2700);
  TH1D *PtISR = (TH1D*) f->Get("h_PtISR");
  PtISR->GetYaxis()->SetTitle("Counts/1 GeV");
  PtISR->GetYaxis()->SetTitleOffset(1.7);
  PtISR->GetXaxis()->SetTitle("Pt[GeV]");
  TCanvas *c_ISRhistos= new TCanvas("c_ISRhistos","different observables from the generated ISR 4vector ",1000,1000);
  c_ISRhistos->Divide(2,2);
  c_ISRhistos->cd(1);
  CthISR->Draw();
  gPad->Update();
  TPaveStats *st41 = (TPaveStats*)CthISR->FindObject("stats");
  st41->SetOptStat(10);
  CthISR->Draw();
  c_ISRhistos->cd(2);
  EtaISR->Draw();
  gPad->Update();
  TPaveStats *st42 = (TPaveStats*)EtaISR->FindObject("stats");
  st42->SetOptStat(10);
  EtaISR->Draw();
  c_ISRhistos->cd(3);
  PhiISR->Draw();
  gPad->Update();
  TPaveStats *st44 = (TPaveStats*)PhiISR->FindObject("stats");
  st44->SetOptStat(10);
  PhiISR->Draw();
  c_ISRhistos->cd(4);
  PtISR->Draw();
  gPad->Update();
  TPaveStats *st44 = (TPaveStats*)PtISR->FindObject("stats");
  st44->SetOptStat(10);
  PtISR->Draw();

  c_ISRhistos->Print("histos.pdf[");
  c_ISRhistos->Print("histos.pdf");
  c_ISRhistos->Close();


  TH1D *EtaHiggs = (TH1D*) f->Get("h_EtaHiggs");
  EtaHiggs->GetYaxis()->SetTitle("Counts/0.1");
  EtaHiggs->GetYaxis()->SetTitleOffset(1.7);
  EtaHiggs->GetXaxis()->SetTitle("#eta");
  TH1D *CthHiggs = (TH1D*) f->Get("h_CthHiggs");
  CthHiggs->GetYaxis()->SetTitle("Counts/0.02");
  CthHiggs->GetYaxis()->SetTitleOffset(1.7);
  CthHiggs->GetYaxis()->SetRangeUser(0,2800);
  CthHiggs->GetXaxis()->SetTitle("Cos(#theta)");
  TH1D *PhiHiggs = (TH1D*) f->Get("h_PhiHiggs");
  PhiHiggs->GetYaxis()->SetTitle("Counts/0.064 rad");
  PhiHiggs->GetYaxis()->SetTitleOffset(1.7);
  PhiHiggs->GetXaxis()->SetTitle("#phi[rad]");
  PhiHiggs->GetYaxis()->SetRangeUser(0,2700);
  TH1D *PtHiggs = (TH1D*) f->Get("h_PtHiggs");
  PtHiggs->GetYaxis()->SetTitle("Counts/1 GeV");
  PtHiggs->GetYaxis()->SetTitleOffset(1.7);
  PtHiggs->GetXaxis()->SetTitle("Pt[GeV]");
  TCanvas *c_Higgshistos= new TCanvas("c_Higgshistos","different observables from the generated Higgs 4vector ",1000,1000);
  c_Higgshistos->Divide(2,2);
  c_Higgshistos->cd(1);
  CthHiggs->Draw();
  gPad->Update();
  TPaveStats *st51 = (TPaveStats*)CthHiggs->FindObject("stats");
  st51->SetOptStat(10);
  CthHiggs->Draw();
  c_Higgshistos->cd(2);
  EtaHiggs->Draw();
  gPad->Update();
  TPaveStats *st52 = (TPaveStats*)EtaHiggs->FindObject("stats");
  st52->SetOptStat(1110);
  EtaHiggs->Draw();
  c_Higgshistos->cd(3);
  PhiHiggs->Draw();
  gPad->Update();
  TPaveStats *st54 = (TPaveStats*)PhiHiggs->FindObject("stats");
  st54->SetOptStat(10);
  PhiHiggs->Draw();
  c_Higgshistos->cd(4);
  PtHiggs->Draw();
  gPad->Update();
  TPaveStats *st54 = (TPaveStats*)PtHiggs->FindObject("stats");
  st54->SetOptStat(10);
  PtHiggs->Draw();

  c_Higgshistos->Print("histos.pdf");
  c_Higgshistos->Close();
  

  TH1D *EtaTau1 = (TH1D*) f->Get("h_EtaTau1");
  EtaTau1->GetYaxis()->SetTitle("Counts/0.1");
  EtaTau1->GetYaxis()->SetTitleOffset(1.7);
  EtaTau1->GetXaxis()->SetTitle("#eta");
  TH1D *CthTau1 = (TH1D*) f->Get("h_CthTau1");
  CthTau1->GetYaxis()->SetTitle("Counts/0.02");
  CthTau1->GetYaxis()->SetTitleOffset(1.7);
  CthTau1->GetYaxis()->SetRangeUser(0,2800);
  CthTau1->GetXaxis()->SetTitle("Cos(#theta)");
  TH1D *PhiTau1 = (TH1D*) f->Get("h_PhiTau1"); 
  PhiTau1->GetYaxis()->SetTitle("Counts/0.064 rad");
  PhiTau1->GetYaxis()->SetTitleOffset(1.7);
  PhiTau1->GetXaxis()->SetTitle("#phi[rad]");
  PhiTau1->GetYaxis()->SetRangeUser(0,2700);
  TH1D *PtTau1 = (TH1D*) f->Get("h_PtTau1");
  PtTau1->GetYaxis()->SetTitle("Counts/1 GeV");
  PtTau1->GetYaxis()->SetTitleOffset(1.7);
  PtTau1->GetXaxis()->SetTitle("Pt[GeV]");
  TH1D *ETau1 = (TH1D*) f->Get("h_ETau1");
  ETau1->GetYaxis()->SetTitle("Counts/1 GeV");
  ETau1->GetYaxis()->SetTitleOffset(1.7);
  ETau1->GetXaxis()->SetTitle("E[GeV]");
  TCanvas *c_tau1histos= new TCanvas("c_tau1histos","different observables from the generated tau1 4vector ",1000,1000);
  c_tau1histos->Divide(2,3);
  c_tau1histos->cd(1);
  CthTau1->Draw();
  gPad->Update();
  TPaveStats *st21 = (TPaveStats*)CthTau1->FindObject("stats");
  st21->SetOptStat(10);
  CthTau1->Draw();
  c_tau1histos->cd(2);
  EtaTau1->Draw();
  gPad->Update();
  TPaveStats *st22 = (TPaveStats*)EtaTau1->FindObject("stats");
  st22->SetOptStat(1110);
  EtaTau1->Draw(); 
  c_tau1histos->cd(3);
  PhiTau1->Draw();
  gPad->Update();
  TPaveStats *st23 = (TPaveStats*)PhiTau1->FindObject("stats");
  st23->SetOptStat(10);
  PhiTau1->Draw();
  c_tau1histos->cd(4);
  PtTau1->Draw();
  gPad->Update();
  TPaveStats *st24 = (TPaveStats*)PtTau1->FindObject("stats");
  st24->SetOptStat(10);
  PtTau1->Draw();
  c_tau1histos->cd(5);
  ETau1->Draw();
  gPad->Update();
  TPaveStats *st25 = (TPaveStats*)ETau1->FindObject("stats");
  st25->SetOptStat(110);
  ETau1->Draw();

  c_tau1histos->Print("histos.pdf");
  c_tau1histos->Close();


  TH1D *EtaTau2 = (TH1D*) f->Get("h_EtaTau2");
  EtaTau2->GetYaxis()->SetTitle("Counts/0.1");
  EtaTau2->GetYaxis()->SetTitleOffset(1.7);
  EtaTau2->GetXaxis()->SetTitle("#eta");
  TH1D *CthTau2 = (TH1D*) f->Get("h_CthTau2");
  CthTau2->GetYaxis()->SetTitle("Counts/0.02");
  CthTau2->GetYaxis()->SetTitleOffset(1.7);
  CthTau2->GetYaxis()->SetRangeUser(0,2800);
  CthTau2->GetXaxis()->SetTitle("Cos(#theta)");
  TH1D *PhiTau2 = (TH1D*) f->Get("h_PhiTau2"); 
  PhiTau2->GetYaxis()->SetTitle("Counts/0.064 rad");
  PhiTau2->GetYaxis()->SetTitleOffset(1.7);
  PhiTau2->GetXaxis()->SetTitle("#phi[rad]");
  PhiTau2->GetYaxis()->SetRangeUser(0,2700);
  TH1D *PtTau2 = (TH1D*) f->Get("h_PtTau2");
  PtTau2->GetYaxis()->SetTitle("Counts/1 GeV");
  PtTau2->GetYaxis()->SetTitleOffset(1.7);
  PtTau2->GetXaxis()->SetTitle("Pt[GeV]");
  TH1D *ETau2 = (TH1D*) f->Get("h_ETau2");
  ETau2->GetYaxis()->SetTitle("Counts/1 GeV");
  ETau2->GetYaxis()->SetTitleOffset(1.7);
  ETau2->GetXaxis()->SetTitle("E[GeV]");
  TCanvas *c_tau2histos= new TCanvas("c_tau2histos","different observables from the generated tau2 4vector ",1000,1000);
  c_tau2histos->Divide(2,3);
  c_tau2histos->cd(1);
  CthTau2->Draw();
  gPad->Update();
  TPaveStats *st31 = (TPaveStats*)CthTau2->FindObject("stats");
  st31->SetOptStat(10);
  CthTau2->Draw();
  c_tau2histos->cd(2);
  EtaTau2->Draw();
  gPad->Update();
  TPaveStats *st32 = (TPaveStats*)EtaTau2->FindObject("stats");
  st32->SetOptStat(1110);
  EtaTau2->Draw(); 
  c_tau2histos->cd(3);
  PhiTau2->Draw();
  gPad->Update();
  TPaveStats *st33 = (TPaveStats*)PhiTau2->FindObject("stats");
  st33->SetOptStat(10);
  PhiTau2->Draw();
  c_tau2histos->cd(4);
  PtTau2->Draw();
  gPad->Update();
  TPaveStats *st34 = (TPaveStats*)PtTau2->FindObject("stats");
  st34->SetOptStat(10);
  PtTau2->Draw();
  c_tau2histos->cd(5);
  ETau2->Draw();
  gPad->Update();
  TPaveStats *st35 = (TPaveStats*)ETau2->FindObject("stats");
  st35->SetOptStat(110);
  ETau2->Draw();
  c_tau2histos->Print("histos.pdf");
  c_tau2histos->Close();



  
  TFile *f = new TFile("controlplots.root","READ");
  TH1D *invariantmass = (TH1D*) f->Get("h_invariantmass");
  invariantmass->GetXaxis()->SetTitle("invariant mass[GeV]");
  invariantmass->GetYaxis()->SetTitle("Counts/0.005GeV");
  TCanvas *c_invariantmass= new TCanvas("invmass","the invariant mass of the two tau",1500,1000);
  invariantmass->Draw();
  gPad->Update();
  TPaveStats *st11 = (TPaveStats*)invariantmass->FindObject("stats");
  st11->SetOptStat(110);
  invariantmass->Draw();
  c_invariantmass->Print("histos.pdf");
  c_invariantmass->Close();

  TH1D *EtaTau1boosted = (TH1D*) f->Get("h_EtaTau1boosted");
  EtaTau1boosted->GetYaxis()->SetTitle("Counts/0.1");
  EtaTau1boosted->GetYaxis()->SetTitleOffset(1.7);
  EtaTau1boosted->GetXaxis()->SetTitle("#eta");
  TH1D *CthTau1boosted = (TH1D*) f->Get("h_CthTau1boosted");
  CthTau1boosted->GetYaxis()->SetTitle("Counts/0.02");
  CthTau1boosted->GetYaxis()->SetTitleOffset(1.7);
  CthTau1boosted->GetYaxis()->SetRangeUser(0,2800);
  CthTau1boosted->GetXaxis()->SetTitle("Cos(#theta)");
  TH1D *PhiTau1boosted = (TH1D*) f->Get("h_PhiTau1boosted");
  PhiTau1boosted->GetYaxis()->SetTitle("Counts/0.064 rad");
  PhiTau1boosted->GetYaxis()->SetTitleOffset(1.7);
  PhiTau1boosted->GetXaxis()->SetTitle("#phi[rad]");
  PhiTau1boosted->GetYaxis()->SetRangeUser(0,2700);
  TH1D *PtTau1boosted = (TH1D*) f->Get("h_PtTau1boosted");
  PtTau1boosted->GetYaxis()->SetTitle("Counts/1 GeV");
  PtTau1boosted->GetYaxis()->SetTitleOffset(1.7);
  PtTau1boosted->GetXaxis()->SetTitle("Pt[GeV]");
  TH1D *ETau1boosted = (TH1D*) f->Get("h_ETau1boosted");
  ETau1boosted->GetYaxis()->SetTitle("Counts/1 GeV");
  ETau1boosted->GetYaxis()->SetTitleOffset(1.7);
  ETau1boosted->GetXaxis()->SetTitle("E[GeV]");
  TCanvas *c_Tau1boostedhistos= new TCanvas("c_Tau1boostedhistos","different observables from the generated Tau1boosted 4vector ",1000,1000);
  c_Tau1boostedhistos->Divide(2,3);
  c_Tau1boostedhistos->cd(1);
  CthTau1boosted->Draw();
  gPad->Update();
  TPaveStats *st61 = (TPaveStats*)CthTau1boosted->FindObject("stats");
  st61->SetOptStat(10);
  CthTau1boosted->Draw();
  c_Tau1boostedhistos->cd(2);
  EtaTau1boosted->Draw();
  gPad->Update();
  TPaveStats *st62 = (TPaveStats*)EtaTau1boosted->FindObject("stats");
  st62->SetOptStat(1110);
  EtaTau1boosted->Draw();
  c_Tau1boostedhistos->cd(3);
  PhiTau1boosted->Draw();
  gPad->Update();
  TPaveStats *st64 = (TPaveStats*)PhiTau1boosted->FindObject("stats");
  st64->SetOptStat(10);
  PhiTau1boosted->Draw();
  c_Tau1boostedhistos->cd(4);
  PtTau1boosted->Draw();
  gPad->Update();
  TPaveStats *st64 = (TPaveStats*)PtTau1boosted->FindObject("stats");
  st64->SetOptStat(10);
  PtTau1boosted->Draw();
  c_Tau1boostedhistos->cd(5);
  ETau1boosted->Draw();
  gPad->Update();
  TPaveStats *st65 = (TPaveStats*)ETau1boosted->FindObject("stats");
  st65->SetOptStat(110);
  ETau1boosted->Draw();

  c_Tau1boostedhistos->Print("histos.pdf");
  c_Tau1boostedhistos->Close();


  TH1D *EtaTau2boosted = (TH1D*) f->Get("h_EtaTau2boosted");
  EtaTau2boosted->GetYaxis()->SetTitle("Counts/0.1");
  EtaTau2boosted->GetYaxis()->SetTitleOffset(1.7);
  EtaTau2boosted->GetXaxis()->SetTitle("#eta");
  TH1D *CthTau2boosted = (TH1D*) f->Get("h_CthTau2boosted");
  CthTau2boosted->GetYaxis()->SetTitle("Counts/0.02");
  CthTau2boosted->GetYaxis()->SetTitleOffset(1.7);
  CthTau2boosted->GetYaxis()->SetRangeUser(0,2800);
  CthTau2boosted->GetXaxis()->SetTitle("Cos(#theta)");
  TH1D *PhiTau2boosted = (TH1D*) f->Get("h_PhiTau2boosted");
  PhiTau2boosted->GetYaxis()->SetTitle("Counts/0.064 rad");
  PhiTau2boosted->GetYaxis()->SetTitleOffset(1.7);
  PhiTau2boosted->GetXaxis()->SetTitle("#phi[rad]");
  PhiTau2boosted->GetYaxis()->SetRangeUser(0,2700);
  TH1D *PtTau2boosted = (TH1D*) f->Get("h_PtTau2boosted");
  PtTau2boosted->GetYaxis()->SetTitle("Counts/1 GeV");
  PtTau2boosted->GetYaxis()->SetTitleOffset(1.7);
  PtTau2boosted->GetXaxis()->SetTitle("Pt[GeV]");
  TH1D *ETau2boosted = (TH1D*) f->Get("h_ETau2boosted");
  ETau2boosted->GetYaxis()->SetTitle("Counts/1 GeV");
  ETau2boosted->GetYaxis()->SetTitleOffset(1.7);
  ETau2boosted->GetXaxis()->SetTitle("E[GeV]");
  TCanvas *c_Tau2boostedhistos= new TCanvas("c_Tau2boostedhistos","different observables from the generated Tau2boosted 4vector ",1000,1000);
  c_Tau2boostedhistos->Divide(2,3);
  c_Tau2boostedhistos->cd(1);
  CthTau2boosted->Draw();
  gPad->Update();
  TPaveStats *st71 = (TPaveStats*)CthTau2boosted->FindObject("stats");
  st71->SetOptStat(10);
  CthTau2boosted->Draw();
  c_Tau2boostedhistos->cd(2);
  EtaTau2boosted->Draw();
  gPad->Update();
  TPaveStats *st72 = (TPaveStats*)EtaTau2boosted->FindObject("stats");
  st72->SetOptStat(1110);
  EtaTau2boosted->Draw();
  c_Tau2boostedhistos->cd(3);
  PhiTau2boosted->Draw();
  gPad->Update();
  TPaveStats *st74 = (TPaveStats*)PhiTau2boosted->FindObject("stats");
  st74->SetOptStat(10);
  PhiTau2boosted->Draw();
  c_Tau2boostedhistos->cd(4);
  PtTau2boosted->Draw();
  gPad->Update();
  TPaveStats *st74 = (TPaveStats*)PtTau2boosted->FindObject("stats");
  st74->SetOptStat(10);
  PtTau2boosted->Draw();
  c_Tau2boostedhistos->cd(5);
  ETau2boosted->Draw();
  gPad->Update();
  TPaveStats *st75 = (TPaveStats*)ETau2boosted->FindObject("stats");
  st75->SetOptStat(110);
  ETau2boosted->Draw();

  c_Tau2boostedhistos->Print("histos.pdf");
  c_Tau2boostedhistos->Close();

  TH1D *invariantmassboosted = (TH1D*) f->Get("h_invmassboosted");
  invariantmassboosted->GetXaxis()->SetTitle("invariant mass[GeV]");
  invariantmassboosted->GetYaxis()->SetTitle("Counts/0.005GeV");
  TCanvas *c_invariantmassboosted= new TCanvas("invmass","the invariant mass of the two boosted tau",1500,1000);
  invariantmassboosted->Draw();
  gPad->Update();
  TPaveStats *ste11 = (TPaveStats*)invariantmassboosted->FindObject("stats");
  ste11->SetOptStat(110);
  invariantmassboosted->Draw();
  c_invariantmassboosted->Print("histos.pdf");
  c_invariantmassboosted->Close();


  TH1D *EtaTau1Vis = (TH1D*) f->Get("h_EtaTau1Vis");
  EtaTau1Vis->GetYaxis()->SetTitle("Counts/0.1");
  EtaTau1Vis->GetYaxis()->SetTitleOffset(1.7);
  EtaTau1Vis->GetXaxis()->SetTitle("#eta");
  TH1D *CthTau1Vis = (TH1D*) f->Get("h_CthTau1Vis");
  CthTau1Vis->GetYaxis()->SetTitle("Counts/0.02");
  CthTau1Vis->GetYaxis()->SetTitleOffset(1.7);
  CthTau1Vis->GetYaxis()->SetRangeUser(0,2800);
  CthTau1Vis->GetXaxis()->SetTitle("Cos(#theta)");
  TH1D *PhiTau1Vis = (TH1D*) f->Get("h_PhiTau1Vis");
  PhiTau1Vis->GetYaxis()->SetTitle("Counts/0.064 rad");
  PhiTau1Vis->GetYaxis()->SetTitleOffset(1.7);
  PhiTau1Vis->GetXaxis()->SetTitle("#phi[rad]");
  PhiTau1Vis->GetYaxis()->SetRangeUser(0,2700);
  TH1D *PtTau1Vis = (TH1D*) f->Get("h_PtTau1Vis");
  PtTau1Vis->GetYaxis()->SetTitle("Counts/1 GeV");
  PtTau1Vis->GetYaxis()->SetTitleOffset(1.7);
  PtTau1Vis->GetXaxis()->SetTitle("Pt[GeV]");
  TH1D *ETau1Vis = (TH1D*) f->Get("h_ETau1Vis");
  ETau1Vis->GetYaxis()->SetTitle("Counts/1 GeV");
  ETau1Vis->GetYaxis()->SetTitleOffset(1.7);
  ETau1Vis->GetXaxis()->SetTitle("E[GeV]");
  TH1D *VisFracTau1 = (TH1D*) f->Get("h_VisFracTau1");
  VisFracTau1->GetYaxis()->SetTitle("Counts/0.01");
  VisFracTau1->GetYaxis()->SetTitleOffset(1.7);
  VisFracTau1->GetXaxis()->SetTitle("E[GeV]");
  TCanvas *c_Tau1Vishistos= new TCanvas("c_Tau1Vishistos","different observables from the generated Tau1Vis 4vector ",1000,1000);
  c_Tau1Vishistos->Divide(2,3);
  c_Tau1Vishistos->cd(1);
  CthTau1Vis->Draw();
  gPad->Update();
  TPaveStats *st81 = (TPaveStats*)CthTau1Vis->FindObject("stats");
  st81->SetOptStat(10);
  CthTau1Vis->Draw();
  c_Tau1Vishistos->cd(2);
  EtaTau1Vis->Draw();
  gPad->Update();
  TPaveStats *st82 = (TPaveStats*)EtaTau1Vis->FindObject("stats");
  st82->SetOptStat(1110);
  EtaTau1Vis->Draw();
  c_Tau1Vishistos->cd(3);
  PhiTau1Vis->Draw();
  gPad->Update();
  TPaveStats *st84 = (TPaveStats*)PhiTau1Vis->FindObject("stats");
  st84->SetOptStat(10);
  PhiTau1Vis->Draw();
  c_Tau1Vishistos->cd(4);
  PtTau1Vis->Draw();
  gPad->Update();
  TPaveStats *st84 = (TPaveStats*)PtTau1Vis->FindObject("stats");
  st84->SetOptStat(1110);
  PtTau1Vis->Draw();
  c_Tau1Vishistos->cd(5);
  ETau1Vis->Draw();
  gPad->Update();
  TPaveStats *st85 = (TPaveStats*)ETau1Vis->FindObject("stats");
  st85->SetOptStat(1110);
  ETau1Vis->Draw();
  c_Tau1Vishistos->cd(6);
  VisFracTau1->Draw();
  gPad->Update();
  TPaveStats *st86 = (TPaveStats*)VisFracTau1->FindObject("stats");
  st86->SetOptStat(10);
  VisFracTau1->Draw();

  c_Tau1Vishistos->Print("histos.pdf");
  c_Tau1Vishistos->Close();

  TH1D *EtaTau2Vis = (TH1D*) f->Get("h_EtaTau2Vis");
  EtaTau2Vis->GetYaxis()->SetTitle("Counts/0.1");
  EtaTau2Vis->GetYaxis()->SetTitleOffset(1.7);
  EtaTau2Vis->GetXaxis()->SetTitle("#eta");
  TH1D *CthTau2Vis = (TH1D*) f->Get("h_CthTau2Vis");
  CthTau2Vis->GetYaxis()->SetTitle("Counts/0.02");
  CthTau2Vis->GetYaxis()->SetTitleOffset(1.7);
  CthTau2Vis->GetYaxis()->SetRangeUser(0,2800);
  CthTau2Vis->GetXaxis()->SetTitle("Cos(#theta)");
  TH1D *PhiTau2Vis = (TH1D*) f->Get("h_PhiTau2Vis");
  PhiTau2Vis->GetYaxis()->SetTitle("Counts/0.064 rad");
  PhiTau2Vis->GetYaxis()->SetTitleOffset(1.7);
  PhiTau2Vis->GetYaxis()->SetRangeUser(0,2700);
  PhiTau2Vis->GetXaxis()->SetTitle("#phi[rad]");
  TH1D *PtTau2Vis = (TH1D*) f->Get("h_PtTau2Vis");
  PtTau2Vis->GetYaxis()->SetTitle("Counts/1 GeV");
  PtTau2Vis->GetYaxis()->SetTitleOffset(1.7);
  PtTau2Vis->GetXaxis()->SetTitle("Pt[GeV]");
  TH1D *ETau2Vis = (TH1D*) f->Get("h_ETau2Vis");
  ETau2Vis->GetYaxis()->SetTitle("Counts/1 GeV");
  ETau2Vis->GetYaxis()->SetTitleOffset(1.7);
  ETau2Vis->GetXaxis()->SetTitle("E[GeV]");
  TH1D *VisFracTau2 = (TH1D*) f->Get("h_VisFracTau2");
  VisFracTau2->GetYaxis()->SetTitle("Counts/0.01 ");
  VisFracTau2->GetYaxis()->SetTitleOffset(1.7);
  VisFracTau2->GetXaxis()->SetTitle("E[GeV]");
  TCanvas *c_Tau2Vishistos= new TCanvas("c_Tau2Vishistos","different observables from the generated Tau2Vis 4vector ",1000,1000);
  c_Tau2Vishistos->Divide(2,3);
  c_Tau2Vishistos->cd(1);
  CthTau2Vis->Draw();
  gPad->Update();
  TPaveStats *st91 = (TPaveStats*)CthTau2Vis->FindObject("stats");
  st91->SetOptStat(10);
  CthTau2Vis->Draw();
  c_Tau2Vishistos->cd(2);
  EtaTau2Vis->Draw();
  gPad->Update();
  TPaveStats *st92 = (TPaveStats*)EtaTau2Vis->FindObject("stats");
  st92->SetOptStat(1110);
  EtaTau2Vis->Draw();
  c_Tau2Vishistos->cd(3);
  PhiTau2Vis->Draw();
  gPad->Update();
  TPaveStats *st94 = (TPaveStats*)PhiTau2Vis->FindObject("stats");
  st94->SetOptStat(10);
  PhiTau2Vis->Draw();
  c_Tau2Vishistos->cd(4);
  PtTau2Vis->Draw();
  gPad->Update();
  TPaveStats *st94 = (TPaveStats*)PtTau2Vis->FindObject("stats");
  st94->SetOptStat(1110);
  PtTau2Vis->Draw();
  c_Tau2Vishistos->cd(5);
  ETau2Vis->Draw();
  gPad->Update();
  TPaveStats *st95 = (TPaveStats*)ETau2Vis->FindObject("stats");
  st95->SetOptStat(1110);
  ETau2Vis->Draw();
  c_Tau2Vishistos->cd(6);
  VisFracTau2->Draw();
  gPad->Update();
  TPaveStats *st96 = (TPaveStats*)VisFracTau2->FindObject("stats");
  st96->SetOptStat(10);
  VisFracTau2->Draw();

  c_Tau2Vishistos->Print("histos.pdf");
  c_Tau2Vishistos->Close();

  //--------------------------------------------------------------------------------------
    THStack *EtaAllTau1= new THStack("EtaAllTau1","Eta from tau1, tau1boosted,tau1vis");
//    EtaAllTau1->Add(EtaTau1);
  //  EtaTau1->SetLineColor(kBlue);
    EtaAllTau1->Add(EtaTau1boosted);
    EtaTau1boosted->SetLineColor(kBlack);
    EtaAllTau1->Add(EtaTau1Vis);
    EtaTau1Vis->SetLineColor(kRed);
    THStack *CthAllTau1= new THStack("CthAllTau1","Cos(theta) from tau1, tau1boosted,tau1vis");
//    CthAllTau1->Add(CthTau1);
  //  CthTau1->SetLineColor(kBlue);
    CthAllTau1->Add(CthTau1boosted);
    CthTau1boosted->SetLineColor(kBlack);
    CthAllTau1->Add(CthTau1Vis);
    CthTau1Vis->SetLineColor(kRed);
    THStack *PhiAllTau1= new THStack("PhiAllTau1","#Phi from tau1, tau1boosted,tau1vis");
   // PhiAllTau1->Add(PhiTau1);
   // PhiTau1->SetLineColor(kBlue);
    PhiAllTau1->Add(PhiTau1boosted);
    PhiTau1boosted->SetLineColor(kBlack);
    PhiAllTau1->Add(PhiTau1Vis);
    PhiTau1Vis->SetLineColor(kRed);
    THStack *PtAllTau1= new THStack("PtAllTau1","Pt from tau1, tau1boosted,tau1vis");
   // PtAllTau1->Add(PtTau1);
   // PtTau1->SetLineColor(kBlue);
    PtAllTau1->Add(PtTau1boosted);
    PtTau1boosted->SetLineColor(kBlack);
    PtAllTau1->Add(PtTau1Vis);
    PtTau1Vis->SetLineColor(kRed);
    THStack *EAllTau1= new THStack("EAllTau1","E from tau1, tau1boosted,tau1vis");
   // EAllTau1->Add(ETau1);
  //  ETau1->SetLineColor(kBlue);
    EAllTau1->Add(ETau1boosted);
    ETau1boosted->SetLineColor(kBlack);
    EAllTau1->Add(ETau1Vis);
    ETau1Vis->SetLineColor(kRed);
    TCanvas *c_Tau1all = new TCanvas("c_Tau1all","different observables from the generated Tau ",1000,1000);
    c_Tau1all->Divide(2,3);
    c_Tau1all->cd(1);
    EtaAllTau1->Draw("nostack");
    gPad->Update();
    EtaAllTau1->GetYaxis()->SetTitle("Counts/0.1");
    EtaAllTau1->GetXaxis()->SetTitle("#eta");
    EtaAllTau1->Draw("nostack");
    c_Tau1all->cd(2);
    CthAllTau1->Draw("nostack");
    gPad->Update();
    CthAllTau1->GetYaxis()->SetTitle("Counts/0.02");
    CthAllTau1->GetXaxis()->SetTitle("Cos(#theta)");
    CthAllTau1->Draw("nostack");
    c_Tau1all->cd(3);
    PhiAllTau1->Draw("nostack");
    gPad->Update();
    PhiAllTau1->GetYaxis()->SetTitle("Counts/0.064 rad");
    PhiAllTau1->GetXaxis()->SetTitle("#phi[rad]");
    PhiAllTau1->Draw("nostack");
    c_Tau1all->cd(4);
    PtAllTau1->Draw("nostack");
    gPad->Update();
    PtAllTau1->GetYaxis()->SetTitle("Counts/1 GeV");
    PtAllTau1->GetYaxis()->SetTitleOffset(1.2);
    PtAllTau1->GetXaxis()->SetTitle("Pt[GeV]");
    PtAllTau1->Draw("nostack");
    c_Tau1all->cd(5);
    EAllTau1->Draw("nostack");
    gPad->Update();
    EAllTau1->GetYaxis()->SetTitle("Counts/1 GeV");
    EAllTau1->GetXaxis()->SetTitle("E[GeV]");
    EAllTau1->GetYaxis()->SetTitleOffset(1.2);
    EAllTau1->Draw("nostack");
    c_Tau1all->cd(6);
    TLegend  *legtau1 = new TLegend(0.1,0.7,0.48,0.9);
    //legtau1->AddEntry(EtaTau1,"Tau 1","l");
    legtau1->AddEntry("EtaTau1boosted","Boosted tau1","L");
    legtau1->AddEntry("EtaTau1Vis","Visible tau1 component","L");
    legtau1->Draw();
    c_Tau1all->Print("histos.pdf");
    c_Tau1all->Close();


    THStack *EtaAllTau2= new THStack("EtaAllTau2","Eta from Tau2, Tau2boosted,Tau2vis");
    //    EtaAllTau2->Add(EtaTau2);
     //   EtaTau2->SetLineColor(kBlue);
        EtaAllTau2->Add(EtaTau2boosted);
        EtaTau2boosted->SetLineColor(kBlack);
        EtaAllTau2->Add(EtaTau2Vis);
        EtaTau2Vis->SetLineColor(kRed);
        THStack *CthAllTau2= new THStack("CthAllTau2","Cos(theta) from Tau2, Tau2boosted,Tau2vis");
       // CthAllTau2->Add(CthTau2);
       // CthTau2->SetLineColor(kBlue);
        CthAllTau2->Add(CthTau2boosted);
        CthTau2boosted->SetLineColor(kBlack);
        CthAllTau2->Add(CthTau2Vis);
        CthTau2Vis->SetLineColor(kRed);
        THStack *PhiAllTau2= new THStack("PhiAllTau2","#Phi from Tau2, Tau2boosted,Tau2vis");
       // PhiAllTau2->Add(PhiTau2);
       // PhiTau2->SetLineColor(kBlue);
        PhiAllTau2->Add(PhiTau2boosted);
        PhiTau2boosted->SetLineColor(kBlack);
        PhiAllTau2->Add(PhiTau2Vis);
        PhiTau2Vis->SetLineColor(kRed);
        THStack *PtAllTau2= new THStack("PtAllTau2","Pt from Tau2, Tau2boosted,Tau2vis");
      //  PtAllTau2->Add(PtTau2);
      //  PtTau2->SetLineColor(kBlue);
        PtAllTau2->Add(PtTau2boosted);
        PtTau2boosted->SetLineColor(kBlack);
        PtAllTau2->Add(PtTau2Vis);
        PtTau2Vis->SetLineColor(kRed);
        THStack *EAllTau2= new THStack("EAllTau2","E from Tau2, Tau2boosted,Tau2vis");
       // EAllTau2->Add(ETau2);
       // ETau2->SetLineColor(kBlue);
        EAllTau2->Add(ETau2boosted);
        ETau2boosted->SetLineColor(kBlack);
        EAllTau2->Add(ETau2Vis);
        ETau2Vis->SetLineColor(kRed);
        TCanvas *c_Tau2all = new TCanvas("c_Tau2all","different observables from the generated Tau ",1000,1000);
        c_Tau2all->Divide(2,3);
        c_Tau2all->cd(1);
        EtaAllTau2->Draw("nostack");
        gPad->Update();
        EtaAllTau2->GetYaxis()->SetTitle("Counts/0.1");
        EtaAllTau2->GetXaxis()->SetTitle("#eta");
        EtaAllTau2->Draw("nostack");
        c_Tau2all->cd(2);
        CthAllTau2->Draw("nostack");
        gPad->Update();
        CthAllTau2->GetYaxis()->SetTitle("Counts/0.02");
        CthAllTau2->GetXaxis()->SetTitle("Cos(#theta)");
        CthAllTau2->Draw("nostack");
        c_Tau2all->cd(3);
        PhiAllTau2->Draw("nostack");
        gPad->Update();
        PhiAllTau2->GetYaxis()->SetTitle("Counts/0.064 rad");
        PhiAllTau2->GetXaxis()->SetTitle("#phi[rad]");
        PhiAllTau2->Draw("nostack");
        c_Tau2all->cd(4);
        PtAllTau2->Draw("nostack");
        gPad->Update();
        PtAllTau2->GetYaxis()->SetTitle("Counts/1 GeV");
        PtAllTau2->GetXaxis()->SetTitle("Pt[GeV]");
        PtAllTau2->GetYaxis()->SetTitleOffset(1.2);
        PtAllTau2->Draw("nostack");
        c_Tau2all->cd(5);
        EAllTau2->Draw("nostack");
        gPad->Update();
        EAllTau2->GetYaxis()->SetTitle("Counts/1 GeV");
        EAllTau2->GetXaxis()->SetTitle("E[GeV]");
        EAllTau2->GetYaxis()->SetTitleOffset(1.2);
        EAllTau2->Draw("nostack");
        c_Tau2all->cd(6);
        TLegend  *legtau2 = new TLegend(0.1,0.7,0.48,0.9);
        //legtau1->AddEntry(EtaTau1,"Tau 1","l");
        legtau2->AddEntry("EtaTau2boosted","Boosted tau1","L");
        legtau2->AddEntry("EtaTau2Vis","Visible tau1 component","L");
        legtau2->Draw();

        c_Tau2all->Print("histos.pdf");
        c_Tau2all->Close();
  //--------------------------------------------------------------------------------------


  TH1D *AbsPtmiss = (TH1D*) f->Get("h_AbsPtmiss");
  AbsPtmiss->GetXaxis()->SetTitle("missing Pt[GeV]");
  AbsPtmiss->GetYaxis()->SetTitle("Counts/1GeV");
  TH1D *Pxmiss = (TH1D*) f->Get("h_Pxmiss");
  Pxmiss->GetXaxis()->SetTitle("missing Px[GeV]");
  Pxmiss->GetYaxis()->SetTitle("Counts/1GeV");
  TH1D *Pymiss = (TH1D*) f->Get("h_Pymiss");
  Pymiss->GetXaxis()->SetTitle("missing Py[GeV]");
  Pymiss->GetYaxis()->SetTitle("Counts/1GeV");
  TH1D *PhiMET = (TH1D*) f->Get("h_PhiMET");
  PhiMET->GetXaxis()->SetTitle("Direction of the missing Pt[rad]");
  PhiMET->GetYaxis()->SetTitle("Counts/0.064rad");

  TCanvas *c_MET= new TCanvas("c_MET","the missing transversal momentum",1500,1000);
  c_MET->Divide(2,2);
  c_MET->cd(1);
  AbsPtmiss->Draw();
  gPad->Update();
  TPaveStats *st101 = (TPaveStats*)AbsPtmiss->FindObject("stats");
  st101->SetOptStat(1110);
  AbsPtmiss->Draw();
  c_MET->cd(2);
  PhiMET->Draw();
  gPad->Update();
  TPaveStats *st102 = (TPaveStats*)PhiMET->FindObject("stats");
  st102->SetOptStat(10);
  PhiMET->Draw();
  c_MET->cd(3);
  Pxmiss->Draw();
  gPad->Update();
  TPaveStats *st103 = (TPaveStats*)Pxmiss->FindObject("stats");
  st103->SetOptStat(10);
  Pxmiss->Draw();
  c_MET->cd(4);
  Pymiss->Draw();
  gPad->Update();
  TPaveStats *st104 = (TPaveStats*)Pymiss->FindObject("stats");
  st104->SetOptStat(10);
  Pymiss->Draw();



  c_MET->Print("histos.pdf");
  c_MET->Close();




  TH1D *AbsPtmisswithsigma = (TH1D*) f->Get("h_AbsPtmisswithsigma");
  AbsPtmisswithsigma->GetXaxis()->SetTitle("missing Pt[GeV]");
  AbsPtmisswithsigma->GetYaxis()->SetTitle("Counts/1GeV");
  TH1D *Pxmisswithsigma = (TH1D*) f->Get("h_Pxmisswithsigma");
  Pxmisswithsigma->GetXaxis()->SetTitle("missing Px[GeV]");
  Pxmisswithsigma->GetYaxis()->SetTitle("Counts/1GeV");
  TH1D *Pymisswithsigma = (TH1D*) f->Get("h_Pymisswithsigma");
  Pymisswithsigma->GetXaxis()->SetTitle("missing Py[GeV]");
  Pymisswithsigma->GetYaxis()->SetTitle("Counts/1GeV");
  TH1D *PhiMETwithsigma = (TH1D*) f->Get("h_PhiMETwithsigma");
  PhiMETwithsigma->GetXaxis()->SetTitle("Direction of the missing Pt[rad]");
  PhiMETwithsigma->GetYaxis()->SetTitle("Counts/0.064rad");
  TCanvas *c_METwithsigma= new TCanvas("c_METsigma","the missing transversal momentum with errors",1500,1000);
  c_METwithsigma->Divide(2,2);
  c_METwithsigma->cd(1);
  AbsPtmisswithsigma->Draw();
  gPad->Update();
  TPaveStats *st111 = (TPaveStats*)AbsPtmisswithsigma->FindObject("stats");
  st111->SetOptStat(1110);
  AbsPtmisswithsigma->Draw();
  c_METwithsigma->cd(2);
  PhiMETwithsigma->Draw();
  gPad->Update();
  TPaveStats *st112 = (TPaveStats*)PhiMETwithsigma->FindObject("stats");
  st112->SetOptStat(10);
  PhiMETwithsigma->Draw();
  c_METwithsigma->cd(3);
  Pxmisswithsigma->Draw();
  gPad->Update();
  TPaveStats *st113 = (TPaveStats*)Pxmisswithsigma->FindObject("stats");
  st113->SetOptStat(10);
  Pxmisswithsigma->Draw();
  c_METwithsigma->cd(4);
  Pymisswithsigma->Draw();
  gPad->Update();
  TPaveStats *st114 = (TPaveStats*)Pymisswithsigma->FindObject("stats");
  st114->SetOptStat(10);
  Pymisswithsigma->Draw();

  c_METwithsigma->Print("histos.pdf");
  c_METwithsigma->Close();

  TH1D *FitFinalChi2=(TH1D*) f->Get("h_FitFinalChi2");
  FitFinalChi2->GetXaxis()->SetTitle("The final chi2 term after the Fit");
  FitFinalChi2->GetXaxis()->SetRangeUser(0,6);
  FitFinalChi2->GetYaxis()->SetTitle("Counts/0.12");
  FitFinalChi2->GetYaxis()->SetTitleOffset(1.2);
  TH1D *FitFinalChi2prob=(TH1D*) f->Get("h_FitFinalChi2prob");
  FitFinalChi2prob->GetXaxis()->SetTitle("Probability of the final chi2");
  FitFinalChi2prob->GetYaxis()->SetRangeUser(0,14500);
  FitFinalChi2prob->GetYaxis()->SetTitleOffset(1.2);
  FitFinalChi2prob->GetYaxis()->SetTitle("Counts/0.05");
  TH1D *fracresulutiontau1=(TH1D*) f->Get("h_fracresulutiontau1");
  fracresulutiontau1->GetXaxis()->SetTitle("Resolution of the energyfraction from tauvis1");
  fracresulutiontau1->GetXaxis()->SetTitleOffset(1.2);
  fracresulutiontau1->GetYaxis()->SetTitleOffset(1.2);
  fracresulutiontau1->GetYaxis()->SetTitle("Counts/0.02");
  TH1D *fracresulutiontau2=(TH1D*) f->Get("h_fracresulutiontau2");
  fracresulutiontau2->GetXaxis()->SetTitle("Resolution of the energyfraction from tauvis2");
  fracresulutiontau2->GetXaxis()->SetTitleOffset(1.2);
  fracresulutiontau2->GetYaxis()->SetTitleOffset(1.2);
  fracresulutiontau2->GetYaxis()->SetTitle("Counts/0.02");
  TH1D *energyresulution1=(TH1D*) f->Get("h_energyresulution1");
  energyresulution1->GetXaxis()->SetTitle("Resolution of the energy from the visible tau1");
  energyresulution1->GetXaxis()->SetTitleOffset(1.2);
  energyresulution1->GetYaxis()->SetTitleOffset(1.5);
  energyresulution1->GetYaxis()->SetTitle("Counts/0.026");
  TH1D *energyresulution2=(TH1D*) f->Get("h_energyresulution2");
  energyresulution2->GetXaxis()->SetTitle("Resolution of the energy from the visible tau2");
  energyresulution2->GetXaxis()->SetTitleOffset(1.2);
  energyresulution2->GetYaxis()->SetTitleOffset(1.5);
  energyresulution2->GetYaxis()->SetTitle("Counts/0.026");
  TCanvas *c_KinFit= new TCanvas("c_KinFit","Histos for the KinFit",1000,1000);
  c_KinFit->Divide(2,3);
  c_KinFit->cd(1);
  FitFinalChi2->Draw();
  gPad->Update();
  TPaveStats *st121 = (TPaveStats*) FitFinalChi2->FindObject("stats");
  st121->SetOptStat(1110);
  FitFinalChi2->Draw();
  c_KinFit->cd(2);
  FitFinalChi2prob->Draw();
  gPad->Update();
  TPaveStats *st122 = (TPaveStats*) FitFinalChi2prob->FindObject("stats");
  st122->SetOptStat(10);
  FitFinalChi2prob->Draw();
  c_KinFit->cd(3);
  fracresulutiontau1->Draw();
  gPad->Update();
  TPaveStats *st123 = (TPaveStats*) fracresulutiontau1->FindObject("stats");
  st123->SetOptStat(1110);
  fracresulutiontau1->Draw();
  c_KinFit->cd(4);
  fracresulutiontau2->Draw();
  gPad->Update();
  TPaveStats *st124 = (TPaveStats*) fracresulutiontau2->FindObject("stats");
  st124->SetOptStat(1110);
  fracresulutiontau2->Draw();
  c_KinFit->cd(5);
  energyresulution1->Draw();
  gPad->Update();
  TPaveStats *st125 = (TPaveStats*) energyresulution1->FindObject("stats");
  st125->SetOptStat(1110);
  energyresulution1->Draw();
  c_KinFit->cd(6);
  energyresulution2->Draw();
  gPad->Update();
  TPaveStats *st126 = (TPaveStats*) energyresulution2->FindObject("stats");
  st126->SetOptStat(1110);
  energyresulution2->Draw();


  c_KinFit->Print("histos.pdf");
  c_KinFit->Print("histos.pdf]");
  c_KinFit->Close();


}
