#include "TFile.h"
#include "TH1D.h"
#include "TCanvas.h"
#include "TPaveStats.h"

void Plotmacro(){
  //gROOT->LoadMacro("tdrstyle.C");
  //setTDRStyle();

  TFile *f = new TFile("controlplots.root","READ");
  TH1D *invariantmass = (TH1D*) f->Get("h_invariantmass");
  invariantmass->GetXaxis()->SetTitle("invariant mass[GeV]");
  invariantmass->GetYaxis()->SetTitle("Counts/1GeV");
  TCanvas *c_invariantmass= new TCanvas("invmass","the invariant mass of the two tau",1500,1000);
  invariantmass->Draw();
  gPad->Update();
  TPaveStats *st11 = (TPaveStats*)invariantmass->FindObject("stats");
  st11->SetOptStat(110);
  invariantmass->Draw();
  c_invariantmass->Print("histos.pdf[");
  c_invariantmass->Print("histos.pdf");
  c_invariantmass->Close();

  TH1D *EtaTau1 = (TH1D*) f->Get("h_EtaTau1");
  EtaTau1->GetYaxis()->SetTitle("Counts/0.1");
  EtaTau1->GetYaxis()->SetTitleOffset(1.7);
  EtaTau1->GetXaxis()->SetTitle("#eta");
  TH1D *CthTau1 = (TH1D*) f->Get("h_CthTau1");
  CthTau1->GetYaxis()->SetTitle("Counts/0.2");
  CthTau1->GetYaxis()->SetTitleOffset(1.7);
  CthTau1->GetYaxis()->SetRangeUser(0,2800);
  CthTau1->GetXaxis()->SetTitle("Cos(#theta)");
  TH1D *PhiTau1 = (TH1D*) f->Get("h_PhiTau1"); 
  PhiTau1->GetYaxis()->SetTitle("Counts/0.062 rad");
  PhiTau1->GetYaxis()->SetTitleOffset(1.7);
  PhiTau1->GetXaxis()->SetTitle("#phi[rad]");
  TH1D *PtTau1 = (TH1D*) f->Get("h_PtTau1");
  PtTau1->GetYaxis()->SetTitle("Counts/0.65 GeV");
  PtTau1->GetYaxis()->SetTitleOffset(1.7);
  PtTau1->GetXaxis()->SetTitle("Pt[GeV]");
  TH1D *ETau1 = (TH1D*) f->Get("h_ETau1");
  ETau1->GetYaxis()->SetTitle("Counts/0.5 GeV");
  ETau1->GetYaxis()->SetTitleOffset(1.7);
  ETau1->GetXaxis()->SetTitle("E[GeV]");
  TCanvas *c_tau1histos= new TCanvas("c_tau1histos","different observables from the generated tau1 4vector ",1000,1000);
  c_tau1histos->Divide(2,3);
  c_tau1histos->cd(1);
  CthTau1->Draw();
  gPad->Update();
  TPaveStats *st21 = (TPaveStats*)CthTau1->FindObject("stats");
  st21->SetOptStat(10);
  CthTau1->Draw();
  c_tau1histos->cd(2);
  EtaTau1->Draw();
  gPad->Update();
  TPaveStats *st22 = (TPaveStats*)EtaTau1->FindObject("stats");
  st22->SetOptStat(1110);
  EtaTau1->Draw(); 
  c_tau1histos->cd(3);
  PhiTau1->Draw();
  gPad->Update();
  TPaveStats *st23 = (TPaveStats*)PhiTau1->FindObject("stats");
  st23->SetOptStat(10);
  PhiTau1->Draw();
  c_tau1histos->cd(4);
  PtTau1->Draw();
  gPad->Update();
  TPaveStats *st24 = (TPaveStats*)PtTau1->FindObject("stats");
  st24->SetOptStat(10);
  PtTau1->Draw();
  c_tau1histos->cd(5);
  ETau1->Draw();
  gPad->Update();
  TPaveStats *st25 = (TPaveStats*)ETau1->FindObject("stats");
  st25->SetOptStat(110);
  ETau1->Draw();
  c_tau1histos->Print("histos.pdf");
  c_tau1histos->Close();
TH1D *EtaTau2 = (TH1D*) f->Get("h_EtaTau2");
  EtaTau2->GetYaxis()->SetTitle("Counts/0.1");
  EtaTau2->GetYaxis()->SetTitleOffset(1.7);
  EtaTau2->GetXaxis()->SetTitle("#eta");
  TH1D *CthTau2 = (TH1D*) f->Get("h_CthTau2");
  CthTau2->GetYaxis()->SetTitle("Counts/0.2");
  CthTau2->GetYaxis()->SetTitleOffset(1.7);
  CthTau2->GetYaxis()->SetRangeUser(0,2800);
  CthTau2->GetXaxis()->SetTitle("Cos(#theta)");
  TH1D *PhiTau2 = (TH1D*) f->Get("h_PhiTau2"); 
  PhiTau2->GetYaxis()->SetTitle("Counts/0.062 rad");
  PhiTau2->GetYaxis()->SetTitleOffset(1.7);
  PhiTau2->GetXaxis()->SetTitle("#phi[rad]");
  TH1D *PtTau2 = (TH1D*) f->Get("h_PtTau2");
  PtTau2->GetYaxis()->SetTitle("Counts/0.65 GeV");
  PtTau2->GetYaxis()->SetTitleOffset(1.7);
  PtTau2->GetXaxis()->SetTitle("Pt[GeV]");
  TH1D *ETau2 = (TH1D*) f->Get("h_ETau2");
  ETau2->GetYaxis()->SetTitle("Counts/0.5 GeV");
  ETau2->GetYaxis()->SetTitleOffset(1.7);
  ETau2->GetXaxis()->SetTitle("E[GeV]");
  TCanvas *c_tau2histos= new TCanvas("c_tau2histos","different observables from the generated tau2 4vector ",1000,1000);
  c_tau2histos->Divide(2,3);
  c_tau2histos->cd(1);
  CthTau2->Draw();
  gPad->Update();
  TPaveStats *st31 = (TPaveStats*)CthTau2->FindObject("stats");
  st31->SetOptStat(10);
  CthTau2->Draw();
  c_tau2histos->cd(2);
  EtaTau2->Draw();
  gPad->Update();
  TPaveStats *st32 = (TPaveStats*)EtaTau2->FindObject("stats");
  st32->SetOptStat(1110);
  EtaTau2->Draw(); 
  c_tau2histos->cd(3);
  PhiTau2->Draw();
  gPad->Update();
  TPaveStats *st33 = (TPaveStats*)PhiTau2->FindObject("stats");
  st33->SetOptStat(10);
  PhiTau2->Draw();
  c_tau2histos->cd(4);
  PtTau2->Draw();
  gPad->Update();
  TPaveStats *st34 = (TPaveStats*)PtTau2->FindObject("stats");
  st34->SetOptStat(10);
  PtTau2->Draw();
  c_tau2histos->cd(5);
  ETau2->Draw();
  gPad->Update();
  TPaveStats *st35 = (TPaveStats*)ETau2->FindObject("stats");
  st35->SetOptStat(110);
  ETau2->Draw();
  c_tau2histos->Print("histos.pdf");
  c_tau2histos->Print("histos.pdf]");

}
