#include "TFile.h"
#include "TH1D.h"
#include "TCanvas.h"
#include "TPaveStats.h"

void Plotmacro(){
  //gROOT->LoadMacro("tdrstyle.C");
  //setTDRStyle();

  TFile *f = new TFile("controlplots.root","READ");
  TH1D *invariantmass = (TH1D*) f->Get("h_invariantmass");
  invariantmass->GetXaxis()->SetTitle("invariant mass[GeV]");
  invariantmass->GetYaxis()->SetTitle("Counts/1GeV");
  TCanvas *c_invariantmass= new TCanvas("invmass","the invariant mass of the two tau",1500,1000);
  invariantmass->Draw();
  gPad->Update();
  TPaveStats *st11 = (TPaveStats*)invariantmass->FindObject("stats");
  st11->SetOptStat(110);
  invariantmass->Draw();
  c_invariantmass->Print("histos.pdf[");
  c_invariantmass->Print("histos.pdf");
  c_invariantmass->Close();

  TH1D *EtaTau1 = (TH1D*) f->Get("h_EtaTau1");
  EtaTau1->GetYaxis()->SetTitle("Counts/0.1");
  EtaTau1->GetYaxis()->SetTitleOffset(1.7);
  EtaTau1->GetXaxis()->SetTitle("#eta");
  TH1D *CthTau1 = (TH1D*) f->Get("h_CthTau1");
  CthTau1->GetYaxis()->SetTitle("Counts/0.02");
  CthTau1->GetYaxis()->SetTitleOffset(1.7);
  CthTau1->GetYaxis()->SetRangeUser(0,2800);
  CthTau1->GetXaxis()->SetTitle("Cos(#theta)");
  TH1D *PhiTau1 = (TH1D*) f->Get("h_PhiTau1"); 
  PhiTau1->GetYaxis()->SetTitle("Counts/0.062 rad");
  PhiTau1->GetYaxis()->SetTitleOffset(1.7);
  PhiTau1->GetXaxis()->SetTitle("#phi[rad]");
  TH1D *PtTau1 = (TH1D*) f->Get("h_PtTau1");
  PtTau1->GetYaxis()->SetTitle("Counts/0.65 GeV");
  PtTau1->GetYaxis()->SetTitleOffset(1.7);
  PtTau1->GetXaxis()->SetTitle("Pt[GeV]");
  TH1D *ETau1 = (TH1D*) f->Get("h_ETau1");
  ETau1->GetYaxis()->SetTitle("Counts/0.5 GeV");
  ETau1->GetYaxis()->SetTitleOffset(1.7);
  ETau1->GetXaxis()->SetTitle("E[GeV]");
  TCanvas *c_tau1histos= new TCanvas("c_tau1histos","different observables from the generated tau1 4vector ",1000,1000);
  c_tau1histos->Divide(2,3);
  c_tau1histos->cd(1);
  CthTau1->Draw();
  gPad->Update();
  TPaveStats *st21 = (TPaveStats*)CthTau1->FindObject("stats");
  st21->SetOptStat(10);
  CthTau1->Draw();
  c_tau1histos->cd(2);
  EtaTau1->Draw();
  gPad->Update();
  TPaveStats *st22 = (TPaveStats*)EtaTau1->FindObject("stats");
  st22->SetOptStat(1110);
  EtaTau1->Draw(); 
  c_tau1histos->cd(3);
  PhiTau1->Draw();
  gPad->Update();
  TPaveStats *st23 = (TPaveStats*)PhiTau1->FindObject("stats");
  st23->SetOptStat(10);
  PhiTau1->Draw();
  c_tau1histos->cd(4);
  PtTau1->Draw();
  gPad->Update();
  TPaveStats *st24 = (TPaveStats*)PtTau1->FindObject("stats");
  st24->SetOptStat(10);
  PtTau1->Draw();
  c_tau1histos->cd(5);
  ETau1->Draw();
  gPad->Update();
  TPaveStats *st25 = (TPaveStats*)ETau1->FindObject("stats");
  st25->SetOptStat(110);
  ETau1->Draw();
  c_tau1histos->Print("histos.pdf");
  c_tau1histos->Close();
TH1D *EtaTau2 = (TH1D*) f->Get("h_EtaTau2");
  EtaTau2->GetYaxis()->SetTitle("Counts/0.1");
  EtaTau2->GetYaxis()->SetTitleOffset(1.7);
  EtaTau2->GetXaxis()->SetTitle("#eta");
  TH1D *CthTau2 = (TH1D*) f->Get("h_CthTau2");
  CthTau2->GetYaxis()->SetTitle("Counts/0.02");
  CthTau2->GetYaxis()->SetTitleOffset(1.7);
  CthTau2->GetYaxis()->SetRangeUser(0,2800);
  CthTau2->GetXaxis()->SetTitle("Cos(#theta)");
  TH1D *PhiTau2 = (TH1D*) f->Get("h_PhiTau2"); 
  PhiTau2->GetYaxis()->SetTitle("Counts/0.062 rad");
  PhiTau2->GetYaxis()->SetTitleOffset(1.7);
  PhiTau2->GetXaxis()->SetTitle("#phi[rad]");
  TH1D *PtTau2 = (TH1D*) f->Get("h_PtTau2");
  PtTau2->GetYaxis()->SetTitle("Counts/0.65 GeV");
  PtTau2->GetYaxis()->SetTitleOffset(1.7);
  PtTau2->GetXaxis()->SetTitle("Pt[GeV]");
  TH1D *ETau2 = (TH1D*) f->Get("h_ETau2");
  ETau2->GetYaxis()->SetTitle("Counts/0.5 GeV");
  ETau2->GetYaxis()->SetTitleOffset(1.7);
  ETau2->GetXaxis()->SetTitle("E[GeV]");
  TCanvas *c_tau2histos= new TCanvas("c_tau2histos","different observables from the generated tau2 4vector ",1000,1000);
  c_tau2histos->Divide(2,3);
  c_tau2histos->cd(1);
  CthTau2->Draw();
  gPad->Update();
  TPaveStats *st31 = (TPaveStats*)CthTau2->FindObject("stats");
  st31->SetOptStat(10);
  CthTau2->Draw();
  c_tau2histos->cd(2);
  EtaTau2->Draw();
  gPad->Update();
  TPaveStats *st32 = (TPaveStats*)EtaTau2->FindObject("stats");
  st32->SetOptStat(1110);
  EtaTau2->Draw(); 
  c_tau2histos->cd(3);
  PhiTau2->Draw();
  gPad->Update();
  TPaveStats *st33 = (TPaveStats*)PhiTau2->FindObject("stats");
  st33->SetOptStat(10);
  PhiTau2->Draw();
  c_tau2histos->cd(4);
  PtTau2->Draw();
  gPad->Update();
  TPaveStats *st34 = (TPaveStats*)PtTau2->FindObject("stats");
  st34->SetOptStat(10);
  PtTau2->Draw();
  c_tau2histos->cd(5);
  ETau2->Draw();
  gPad->Update();
  TPaveStats *st35 = (TPaveStats*)ETau2->FindObject("stats");
  st35->SetOptStat(110);
  ETau2->Draw();
  c_tau2histos->Print("histos.pdf");
  c_tau2histos->Close();


  TH1D *EtaISR = (TH1D*) f->Get("h_EtaISR");
    EtaISR->GetYaxis()->SetTitle("Counts/0.12");
    EtaISR->GetYaxis()->SetTitleOffset(1.7);
    EtaISR->GetXaxis()->SetTitle("#eta");
    TH1D *CthISR = (TH1D*) f->Get("h_CthISR");
    CthISR->GetYaxis()->SetTitle("Counts/0.02");
    CthISR->GetYaxis()->SetTitleOffset(1.7);
    CthISR->GetYaxis()->SetRangeUser(0,2800);
    CthISR->GetXaxis()->SetTitle("Cos(#theta)");
    TH1D *PhiISR = (TH1D*) f->Get("h_PhiISR");
    PhiISR->GetYaxis()->SetTitle("Counts/0.062 rad");
    PhiISR->GetYaxis()->SetTitleOffset(1.7);
    PhiISR->GetXaxis()->SetTitle("#phi[rad]");
    TH1D *PtISR = (TH1D*) f->Get("h_PtISR");
    PtISR->GetYaxis()->SetTitle("Counts/0.1 GeV");
    PtISR->GetYaxis()->SetTitleOffset(1.7);
    PtISR->GetXaxis()->SetTitle("Pt[GeV]");
    TCanvas *c_ISRhistos= new TCanvas("c_ISRhistos","different observables from the generated ISR 4vector ",1000,1000);
    c_ISRhistos->Divide(2,2);
    c_ISRhistos->cd(1);
    CthISR->Draw();
    gPad->Update();
    TPaveStats *st41 = (TPaveStats*)CthISR->FindObject("stats");
    st41->SetOptStat(10);
    CthISR->Draw();
    c_ISRhistos->cd(2);
    EtaISR->Draw();
    gPad->Update();
    TPaveStats *st42 = (TPaveStats*)EtaISR->FindObject("stats");
    st42->SetOptStat(10);
    EtaISR->Draw();
    c_ISRhistos->cd(3);
    PhiISR->Draw();
    gPad->Update();
    TPaveStats *st44 = (TPaveStats*)PhiISR->FindObject("stats");
    st44->SetOptStat(10);
    PhiISR->Draw();
    c_ISRhistos->cd(4);
    PtISR->Draw();
    gPad->Update();
    TPaveStats *st44 = (TPaveStats*)PtISR->FindObject("stats");
    st44->SetOptStat(10);
    PtISR->Draw();

    c_ISRhistos->Print("histos.pdf");
    c_ISRhistos->Close();


    TH1D *EtaHiggs = (TH1D*) f->Get("h_EtaHiggs");
        EtaHiggs->GetYaxis()->SetTitle("Counts/0.1");
        EtaHiggs->GetYaxis()->SetTitleOffset(1.7);
        EtaHiggs->GetXaxis()->SetTitle("#eta");
        TH1D *CthHiggs = (TH1D*) f->Get("h_CthHiggs");
        CthHiggs->GetYaxis()->SetTitle("Counts/0.02");
        CthHiggs->GetYaxis()->SetTitleOffset(1.7);
        CthHiggs->GetYaxis()->SetRangeUser(0,2800);
        CthHiggs->GetXaxis()->SetTitle("Cos(#theta)");
        TH1D *PhiHiggs = (TH1D*) f->Get("h_PhiHiggs");
        PhiHiggs->GetYaxis()->SetTitle("Counts/0.062 rad");
        PhiHiggs->GetYaxis()->SetTitleOffset(1.7);
        PhiHiggs->GetXaxis()->SetTitle("#phi[rad]");
        TH1D *PtHiggs = (TH1D*) f->Get("h_PtHiggs");
        PtHiggs->GetYaxis()->SetTitle("Counts/0.1 GeV");
        PtHiggs->GetYaxis()->SetTitleOffset(1.7);
        PtHiggs->GetXaxis()->SetTitle("Pt[GeV]");
        TCanvas *c_Higgshistos= new TCanvas("c_Higgshistos","different observables from the generated Higgs 4vector ",1000,1000);
        c_Higgshistos->Divide(2,2);
        c_Higgshistos->cd(1);
        CthHiggs->Draw();
        gPad->Update();
        TPaveStats *st51 = (TPaveStats*)CthHiggs->FindObject("stats");
        st51->SetOptStat(10);
        CthHiggs->Draw();
        c_Higgshistos->cd(2);
        EtaHiggs->Draw();
        gPad->Update();
        TPaveStats *st52 = (TPaveStats*)EtaHiggs->FindObject("stats");
        st52->SetOptStat(1110);
        EtaHiggs->Draw();
        c_Higgshistos->cd(3);
        PhiHiggs->Draw();
        gPad->Update();
        TPaveStats *st54 = (TPaveStats*)PhiHiggs->FindObject("stats");
        st54->SetOptStat(10);
        PhiHiggs->Draw();
        c_Higgshistos->cd(4);
        PtHiggs->Draw();
        gPad->Update();
        TPaveStats *st54 = (TPaveStats*)PtHiggs->FindObject("stats");
        st54->SetOptStat(10);
        PtHiggs->Draw();

        c_Higgshistos->Print("histos.pdf");
        c_Higgshistos->Close();


        TH1D *EtaTau1boosted = (TH1D*) f->Get("h_EtaTau1boosted");
               EtaTau1boosted->GetYaxis()->SetTitle("Counts/0.1");
               EtaTau1boosted->GetYaxis()->SetTitleOffset(1.7);
               EtaTau1boosted->GetXaxis()->SetTitle("#eta");
               TH1D *CthTau1boosted = (TH1D*) f->Get("h_CthTau1boosted");
               CthTau1boosted->GetYaxis()->SetTitle("Counts/0.02");
               CthTau1boosted->GetYaxis()->SetTitleOffset(1.7);
               CthTau1boosted->GetYaxis()->SetRangeUser(0,2800);
               CthTau1boosted->GetXaxis()->SetTitle("Cos(#theta)");
               TH1D *PhiTau1boosted = (TH1D*) f->Get("h_PhiTau1boosted");
               PhiTau1boosted->GetYaxis()->SetTitle("Counts/0.062 rad");
               PhiTau1boosted->GetYaxis()->SetTitleOffset(1.7);
               PhiTau1boosted->GetXaxis()->SetTitle("#phi[rad]");
               TH1D *PtTau1boosted = (TH1D*) f->Get("h_PtTau1boosted");
               PtTau1boosted->GetYaxis()->SetTitle("Counts/0.1 GeV");
               PtTau1boosted->GetYaxis()->SetTitleOffset(1.7);
               PtTau1boosted->GetXaxis()->SetTitle("Pt[GeV]");
               TCanvas *c_Tau1boostedhistos= new TCanvas("c_Tau1boostedhistos","different observables from the generated Tau1boosted 4vector ",1000,1000);
               c_Tau1boostedhistos->Divide(2,2);
               c_Tau1boostedhistos->cd(1);
               CthTau1boosted->Draw();
               gPad->Update();
               TPaveStats *st61 = (TPaveStats*)CthTau1boosted->FindObject("stats");
               st61->SetOptStat(10);
               CthTau1boosted->Draw();
               c_Tau1boostedhistos->cd(2);
               EtaTau1boosted->Draw();
               gPad->Update();
               TPaveStats *st62 = (TPaveStats*)EtaTau1boosted->FindObject("stats");
               st62->SetOptStat(1110);
               EtaTau1boosted->Draw();
               c_Tau1boostedhistos->cd(3);
               PhiTau1boosted->Draw();
               gPad->Update();
               TPaveStats *st64 = (TPaveStats*)PhiTau1boosted->FindObject("stats");
               st64->SetOptStat(10);
               PhiTau1boosted->Draw();
               c_Tau1boostedhistos->cd(4);
               PtTau1boosted->Draw();
               gPad->Update();
               TPaveStats *st64 = (TPaveStats*)PtTau1boosted->FindObject("stats");
               st64->SetOptStat(10);
               PtTau1boosted->Draw();

               c_Tau1boostedhistos->Print("histos.pdf");
               c_Tau1boostedhistos->Close();


               TH1D *EtaTau2boosted = (TH1D*) f->Get("h_EtaTau2boosted");
                              EtaTau2boosted->GetYaxis()->SetTitle("Counts/0.1");
                              EtaTau2boosted->GetYaxis()->SetTitleOffset(1.7);
                              EtaTau2boosted->GetXaxis()->SetTitle("#eta");
                              TH1D *CthTau2boosted = (TH1D*) f->Get("h_CthTau2boosted");
                              CthTau2boosted->GetYaxis()->SetTitle("Counts/0.02");
                              CthTau2boosted->GetYaxis()->SetTitleOffset(1.7);
                              CthTau2boosted->GetYaxis()->SetRangeUser(0,2800);
                              CthTau2boosted->GetXaxis()->SetTitle("Cos(#theta)");
                              TH1D *PhiTau2boosted = (TH1D*) f->Get("h_PhiTau2boosted");
                              PhiTau2boosted->GetYaxis()->SetTitle("Counts/0.072 rad");
                              PhiTau2boosted->GetYaxis()->SetTitleOffset(1.7);
                              PhiTau2boosted->GetXaxis()->SetTitle("#phi[rad]");
                              TH1D *PtTau2boosted = (TH1D*) f->Get("h_PtTau2boosted");
                              PtTau2boosted->GetYaxis()->SetTitle("Counts/0.1 GeV");
                              PtTau2boosted->GetYaxis()->SetTitleOffset(1.7);
                              PtTau2boosted->GetXaxis()->SetTitle("Pt[GeV]");
                              TCanvas *c_Tau2boostedhistos= new TCanvas("c_Tau2boostedhistos","different observables from the generated Tau2boosted 4vector ",1000,1000);
                              c_Tau2boostedhistos->Divide(2,2);
                              c_Tau2boostedhistos->cd(1);
                              CthTau2boosted->Draw();
                              gPad->Update();
                              TPaveStats *st71 = (TPaveStats*)CthTau2boosted->FindObject("stats");
                              st71->SetOptStat(10);
                              CthTau2boosted->Draw();
                              c_Tau2boostedhistos->cd(2);
                              EtaTau2boosted->Draw();
                              gPad->Update();
                              TPaveStats *st72 = (TPaveStats*)EtaTau2boosted->FindObject("stats");
                              st72->SetOptStat(1110);
                              EtaTau2boosted->Draw();
                              c_Tau2boostedhistos->cd(3);
                              PhiTau2boosted->Draw();
                              gPad->Update();
                              TPaveStats *st74 = (TPaveStats*)PhiTau2boosted->FindObject("stats");
                              st74->SetOptStat(10);
                              PhiTau2boosted->Draw();
                              c_Tau2boostedhistos->cd(4);
                              PtTau2boosted->Draw();
                              gPad->Update();
                              TPaveStats *st74 = (TPaveStats*)PtTau2boosted->FindObject("stats");
                              st74->SetOptStat(10);
                              PtTau2boosted->Draw();

                              c_Tau2boostedhistos->Print("histos.pdf");
                              c_Tau2boostedhistos->Close();

                              TH1D *EtaTau1Vis = (TH1D*) f->Get("h_EtaTau1Vis");
                                             EtaTau1Vis->GetYaxis()->SetTitle("Counts/0.1");
                                             EtaTau1Vis->GetYaxis()->SetTitleOffset(1.7);
                                             EtaTau1Vis->GetXaxis()->SetTitle("#eta");
                                             TH1D *CthTau1Vis = (TH1D*) f->Get("h_CthTau1Vis");
                                             CthTau1Vis->GetYaxis()->SetTitle("Counts/0.02");
                                             CthTau1Vis->GetYaxis()->SetTitleOffset(1.7);
                                             CthTau1Vis->GetYaxis()->SetRangeUser(0,2800);
                                             CthTau1Vis->GetXaxis()->SetTitle("Cos(#theta)");
                                             TH1D *PhiTau1Vis = (TH1D*) f->Get("h_PhiTau1Vis");
                                             PhiTau1Vis->GetYaxis()->SetTitle("Counts/0.082 rad");
                                             PhiTau1Vis->GetYaxis()->SetTitleOffset(1.7);
                                             PhiTau1Vis->GetXaxis()->SetTitle("#phi[rad]");
                                             TH1D *PtTau1Vis = (TH1D*) f->Get("h_PtTau1Vis");
                                             PtTau1Vis->GetYaxis()->SetTitle("Counts/0.1 GeV");
                                             PtTau1Vis->GetYaxis()->SetTitleOffset(1.7);
                                             PtTau1Vis->GetXaxis()->SetTitle("Pt[GeV]");
                                             TH1D *ETau1Vis = (TH1D*) f->Get("h_ETau1Vis");
                                             ETau1Vis->GetYaxis()->SetTitle("Counts/0.1 GeV");
                                             ETau1Vis->GetYaxis()->SetTitleOffset(1.7);
                                             ETau1Vis->GetXaxis()->SetTitle("E[GeV]");
                                             TH1D *VisFracTau1 = (TH1D*) f->Get("h_VisFracTau1");
                                             VisFracTau1->GetYaxis()->SetTitle("Counts/0.1 GeV");
                                             VisFracTau1->GetYaxis()->SetTitleOffset(1.7);
                                             VisFracTau1->GetXaxis()->SetTitle("E[GeV]");
                                             TCanvas *c_Tau1Vishistos= new TCanvas("c_Tau1Vishistos","different observables from the generated Tau1Vis 4vector ",1000,1000);
                                             c_Tau1Vishistos->Divide(2,3);
                                             c_Tau1Vishistos->cd(1);
                                             CthTau1Vis->Draw();
                                             gPad->Update();
                                             TPaveStats *st81 = (TPaveStats*)CthTau1Vis->FindObject("stats");
                                             st81->SetOptStat(10);
                                             CthTau1Vis->Draw();
                                             c_Tau1Vishistos->cd(2);
                                             EtaTau1Vis->Draw();
                                             gPad->Update();
                                             TPaveStats *st82 = (TPaveStats*)EtaTau1Vis->FindObject("stats");
                                             st82->SetOptStat(1110);
                                             EtaTau1Vis->Draw();
                                             c_Tau1Vishistos->cd(3);
                                             PhiTau1Vis->Draw();
                                             gPad->Update();
                                             TPaveStats *st84 = (TPaveStats*)PhiTau1Vis->FindObject("stats");
                                             st84->SetOptStat(10);
                                             PhiTau1Vis->Draw();
                                             c_Tau1Vishistos->cd(4);
                                             PtTau1Vis->Draw();
                                             gPad->Update();
                                             TPaveStats *st84 = (TPaveStats*)PtTau1Vis->FindObject("stats");
                                             st84->SetOptStat(1110);
                                             PtTau1Vis->Draw();
                                             c_Tau1Vishistos->cd(5);
                                             ETau1Vis->Draw();
                                             gPad->Update();
                                             TPaveStats *st85 = (TPaveStats*)ETau1Vis->FindObject("stats");
                                             st85->SetOptStat(1110);
                                             ETau1Vis->Draw();
                                             c_Tau1Vishistos->cd(6);
                                             VisFracTau1->Draw();
                                             gPad->Update();
                                             TPaveStats *st86 = (TPaveStats*)VisFracTau1->FindObject("stats");
                                             st86->SetOptStat(10);
                                             VisFracTau1->Draw();

                                             c_Tau1Vishistos->Print("histos.pdf");
                                             c_Tau1Vishistos->Close();
                                             TH1D *EtaTau2Vis = (TH1D*) f->Get("h_EtaTau2Vis");
                                                                                          EtaTau2Vis->GetYaxis()->SetTitle("Counts/0.1");
                                                                                          EtaTau2Vis->GetYaxis()->SetTitleOffset(1.7);
                                                                                          EtaTau2Vis->GetXaxis()->SetTitle("#eta");
                                                                                          TH1D *CthTau2Vis = (TH1D*) f->Get("h_CthTau2Vis");
                                                                                          CthTau2Vis->GetYaxis()->SetTitle("Counts/0.02");
                                                                                          CthTau2Vis->GetYaxis()->SetTitleOffset(1.7);
                                                                                          CthTau2Vis->GetYaxis()->SetRangeUser(0,2800);
                                                                                          CthTau2Vis->GetXaxis()->SetTitle("Cos(#theta)");
                                                                                          TH1D *PhiTau2Vis = (TH1D*) f->Get("h_PhiTau2Vis");
                                                                                          PhiTau2Vis->GetYaxis()->SetTitle("Counts/0.092 rad");
                                                                                          PhiTau2Vis->GetYaxis()->SetTitleOffset(1.7);
                                                                                          PhiTau2Vis->GetXaxis()->SetTitle("#phi[rad]");
                                                                                          TH1D *PtTau2Vis = (TH1D*) f->Get("h_PtTau2Vis");
                                                                                          PtTau2Vis->GetYaxis()->SetTitle("Counts/0.1 GeV");
                                                                                          PtTau2Vis->GetYaxis()->SetTitleOffset(1.7);
                                                                                          PtTau2Vis->GetXaxis()->SetTitle("Pt[GeV]");
                                                                                          TH1D *ETau2Vis = (TH1D*) f->Get("h_ETau2Vis");
                                                                                          ETau2Vis->GetYaxis()->SetTitle("Counts/0.1 GeV");
                                                                                          ETau2Vis->GetYaxis()->SetTitleOffset(1.7);
                                                                                          ETau2Vis->GetXaxis()->SetTitle("E[GeV]");
                                                                                          TH1D *VisFracTau2 = (TH1D*) f->Get("h_VisFracTau2");
                                                                                          VisFracTau2->GetYaxis()->SetTitle("Counts/0.1 GeV");
                                                                                          VisFracTau2->GetYaxis()->SetTitleOffset(1.7);
                                                                                          VisFracTau2->GetXaxis()->SetTitle("E[GeV]");
                                                                                          TCanvas *c_Tau2Vishistos= new TCanvas("c_Tau2Vishistos","different observables from the generated Tau2Vis 4vector ",1000,1000);
                                                                                          c_Tau2Vishistos->Divide(2,3);
                                                                                          c_Tau2Vishistos->cd(1);
                                                                                          CthTau2Vis->Draw();
                                                                                          gPad->Update();
                                                                                          TPaveStats *st91 = (TPaveStats*)CthTau2Vis->FindObject("stats");
                                                                                          st91->SetOptStat(10);
                                                                                          CthTau2Vis->Draw();
                                                                                          c_Tau2Vishistos->cd(2);
                                                                                          EtaTau2Vis->Draw();
                                                                                          gPad->Update();
                                                                                          TPaveStats *st92 = (TPaveStats*)EtaTau2Vis->FindObject("stats");
                                                                                          st92->SetOptStat(1110);
                                                                                          EtaTau2Vis->Draw();
                                                                                          c_Tau2Vishistos->cd(3);
                                                                                          PhiTau2Vis->Draw();
                                                                                          gPad->Update();
                                                                                          TPaveStats *st94 = (TPaveStats*)PhiTau2Vis->FindObject("stats");
                                                                                          st94->SetOptStat(10);
                                                                                          PhiTau2Vis->Draw();
                                                                                          c_Tau2Vishistos->cd(4);
                                                                                          PtTau2Vis->Draw();
                                                                                          gPad->Update();
                                                                                          TPaveStats *st94 = (TPaveStats*)PtTau2Vis->FindObject("stats");
                                                                                          st94->SetOptStat(1110);
                                                                                          PtTau2Vis->Draw();
                                                                                          c_Tau2Vishistos->cd(5);
                                                                                          ETau2Vis->Draw();
                                                                                          gPad->Update();
                                                                                          TPaveStats *st95 = (TPaveStats*)ETau2Vis->FindObject("stats");
                                                                                          st95->SetOptStat(1110);
                                                                                          ETau2Vis->Draw();
                                                                                          c_Tau2Vishistos->cd(6);
                                                                                          VisFracTau2->Draw();
                                                                                          gPad->Update();
                                                                                          TPaveStats *st96 = (TPaveStats*)VisFracTau2->FindObject("stats");
                                                                                          st96->SetOptStat(10);
                                                                                          VisFracTau2->Draw();

                                                                                          c_Tau2Vishistos->Print("histos.pdf");
                                                                                          c_Tau2Vishistos->Close();


                                                                                          TH1D *AbsPtmiss = (TH1D*) f->Get("h_AbsPtmiss");
                                                                                          AbsPtmiss->GetXaxis()->SetTitle("missing Pt[GeV]");
                                                                                          AbsPtmiss->GetYaxis()->SetTitle("Counts/1GeV");
                                                                                           TCanvas *c_MET= new TCanvas("c_MET","the missing transversal momentum",1500,1000);
 AbsPtmiss->Draw();
                                                                                            gPad->Update();
                                                                                            TPaveStats *st101 = (TPaveStats*)AbsPtmiss->FindObject("stats");
                                                                                            st101->SetOptStat(1110);
                                                                                            AbsPtmiss->Draw();
                                                                                            c_MET->Print("histos.pdf");
                                                                                            c_MET->Close();




TH1D *AbsPtmisswithsigma = (TH1D*) f->Get("h_AbsPtmisswithsigma");
                                                                                           AbsPtmisswithsigma->GetXaxis()->SetTitle("missing Pt[GeV]");
                                                                                           AbsPtmisswithsigma->GetYaxis()->SetTitle("Counts/1GeV");
                                                                                            TCanvas *c_METsigma= new TCanvas("c_METsigma","the missing transversal momentum with errors",1500,1000);
                                                                                            AbsPtmisswithsigma->Draw();
                                                                                               gPad->Update();
                                                                      TPaveStats *st111 = (TPaveStats*)AbsPtmisswithsigma->FindObject("stats");
                                                                                        st111->SetOptStat(1110);
                                                                                        AbsPtmisswithsigma->Draw();
                                                                                            c_METsigma->Print("histos.pdf");


  c_METsigma->Print("histos.pdf]");
  c_METsigma->Close();

}
